swagger: "2.0"
info:
  title: mySampleAPI
  description: API Walk through.
  version: 1.0.0

host: APIgateT2.apigateway.assig3-418322.cloud.goog
basePath: /
schemes:
  - https
  - http

paths:
  /add:
    post:
      operationId: add
      summary: Add function
      produces:
        - application/json
      responses:
        200:
          description: OK
      x-google-backend:
        address: https://addapp-emlsfkyuka-uc.a.run.app
  /mul:
    post:
      operationId: mul
      summary: Multiply function
      produces:
        - application/json
      responses:
        200:
          description: OK
      x-google-backend:
        address: https://mulapp-emlsfkyuka-uc.a.run.app
  /div:
    post:
      operationId: div
      summary: Divide function
      produces:
        - application/json
      responses:
        200:
          description: OK
      x-google-backend:
        address: https://divapp-emlsfkyuka-uc.a.run.app
  /sub:
    post:
      operationId: sub
      summary: Subtract function
      produces:
        - application/json
      responses:
        200:
          description: OK
      x-google-backend:
        address: https://subapp-emlsfkyuka-uc.a.run.app